name: branch-latest-tests

on:
  push:
    branches:
      - latest
      - latest-test
  pull_request:
    branches:
      - latest
  schedule:
    - cron: "0 0 * * 0"

jobs:

  test-in-php81:

    name: latest - ${{ matrix.os }} - PHP ${{ matrix.php }} - TestBench ${{ matrix.testbench }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: [8.1]
        phpunit: [^9.5.10]
        testbench: [^7.0, ^6.22]
        dependency-prefer: [prefer-stable, prefer-lowest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo_mysql, pdo_sqlite
          coverage: none

      # find out composer's cache directory on the current os - for the "Cache dependencies (composer)" step below
      - name: Determine composer's cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies (composer)
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-testbench-${{ matrix.testbench }}-os-${{ matrix.os }}-dependency-prefer-${{ matrix.dependency-prefer }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies (composer)
        run: |
          composer remove "rector/rector" --dev --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit

  test-in-php74: # used to test with the older versions of laravel

    name: latest - ${{ matrix.os }} - PHP ${{ matrix.php }} - TestBench ${{ matrix.testbench }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: [7.4]
        testbench: [^6.0, ^5.0, ^4.0, ^3.8.1, 3.7.*, 3.6.*, 3.5.*, 3.4.*]
        dependency-prefer: [prefer-stable, prefer-lowest]
        include:
          - testbench: ^6.0
            phpunit: "^6.0 | ^7.0 | ^8.0 | ^9.0"
          - testbench: ^5.0
            phpunit: "^6.0 | ^7.0 | ^8.0 | ^9.0"
          - testbench: ^4.0
            phpunit: "^6.0 | ^7.0 | ^8.0 | ^9.0"
          - testbench: ^3.8.1
            phpunit: "^6.0 | ^7.0 | ^8.0 | ^9.0"
          - testbench: 3.7.*
            phpunit: "^6.0 | ^7.0 | ^8.0 | ^9.0"
          - testbench: 3.6.*
            phpunit: "^6.0 | ^7.0 | ^8.0 | ^9.0"
          - testbench: 3.5.*
            phpunit: ~6.0
          - testbench: 3.4.*
            phpunit: ~5.7
        exclude:
          - testbench: ^3.8.1
            dependency-prefer: prefer-lowest
          - testbench: 3.7.*
            dependency-prefer: prefer-lowest
          - testbench: 3.6.*
            dependency-prefer: prefer-lowest
          - testbench: 3.5.*
            dependency-prefer: prefer-lowest
          - testbench: 3.4.*
            dependency-prefer: prefer-lowest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo_mysql, pdo_sqlite
          coverage: none

      # find out composer's cache directory on the current os - for the "Cache dependencies (composer)" step below
      - name: Determine composer's cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies (composer)
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-testbench-${{ matrix.testbench }}-os-${{ matrix.os }}-dependency-prefer-${{ matrix.dependency-prefer }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies (composer)
        run: |
          composer remove "rector/rector" --dev --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
